### ISSUE TITLE
Frame for Table Shield

### ISSUE THREAD

**Issue by jenkaitor** [CitySportsClub/Human-Resource#12]
Good Day Sir Jef,

Purpose for request: Table Shield for Pag-ibig Staffs 
When used: Oct 16, 2020 (Friday) for the capturing of Pag-ibig Loyalty Card. But it must set-up on Oct. 15 (Thursday).

Note: For Plastic cover, I already coordinate with Ms Sharon. 

Thank you.

**Comment by buildingengineers** [comment]
noted on this miss Jen
